# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish GoalspireBackend/GoalspireBackend.csproj -c Release -o build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/**
        if-no-files-found: error
        
  docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x # Change to 7.0.x later
    - name: Install Swashbuckle CLI
      run: dotnet tool install --version 6.4.0 --global Swashbuckle.AspNetCore.Cli
    - name: Generate OpenAPI
      run: dotnet swagger tofile --output openapi.json build/GoalspireBackend.dll v1
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: docs
        spec-file: openapi.json
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
      
    

