# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  REGISTRY: 'ghcr.io'
  IMAGE_NAME: 'goalspiredev/backend'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore GoalspireBackend/GoalspireBackend.csproj
    - name: Build
      run: dotnet build GoalspireBackend/GoalspireBackend.csproj --no-restore -o build
    - name: Install Swashbuckle CLI
      run: dotnet tool install --version 6.4.0 --global Swashbuckle.AspNetCore.Cli
    - name: Generate OpenAPI
      run: swagger tofile --output openapi.json GoalspireBackend/build/GoalspireBackend.dll v1
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: docs
        spec-file: openapi.json
    - name: Push to branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        publish_branch: docs
      
    

